import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy — Empower",
  description: "Empower privacy policy: how we collect, use, and protect your data.",
};

export default function PrivacyPage() {
  return (
    <section className="py-16 md:py-24">
      <div className="max-w-[800px] mx-auto px-6">
        <h1 className="text-[2rem] md:text-[2.4rem] font-bold text-brand-primary mb-8">
          Privacy Policy
        </h1>

        <div className="prose-custom space-y-6 text-[0.95rem] text-ink leading-relaxed">
          <p className="text-slate">
            <strong>Effective date:</strong> Upon publication
          </p>

          <h2 className="text-[1.2rem] font-semibold text-brand-primary mt-8">
            1. Who we are
          </h2>
          <p>
            Empower (&quot;we,&quot; &quot;us,&quot; &quot;our&quot;) is a special
            education consultancy serving Ontario schools and school boards. This
            privacy policy explains how we collect, use, and protect information
            gathered through our website and services.
          </p>

          <h2 className="text-[1.2rem] font-semibold text-brand-primary mt-8">
            2. Information we collect
          </h2>
          <p>We collect the following categories of information:</p>
          <ul className="list-disc ml-6 space-y-1">
            <li>
              <strong>Contact information:</strong> name, email address, phone
              number, role/title, and school or board affiliation provided through
              our contact form.
            </li>
            <li>
              <strong>School profile data:</strong> organization name, type,
              enrolment ranges, grade ranges, and aggregate special education
              information submitted through our Program Builder tool. This data is
              school-level and aggregate only.
            </li>
            <li>
              <strong>Generated program plans:</strong> AI-generated program
              frameworks produced by our Program Builder tool.
            </li>
          </ul>

          <h2 className="text-[1.2rem] font-semibold text-brand-primary mt-8">
            3. What we do NOT collect
          </h2>
          <p>
            We do <strong>not</strong> collect any individually identifiable student
            information, including but not limited to: student names, Ontario
            Education Numbers (OEN), individual diagnoses, Individual Education Plans
            (IEPs), or any other personal information about individual students. Our
            forms are designed to capture school-level and aggregate data only.
          </p>

          <h2 className="text-[1.2rem] font-semibold text-brand-primary mt-8">
            4. How we use your information
          </h2>
          <ul className="list-disc ml-6 space-y-1">
            <li>To generate AI-powered program framework drafts for your school</li>
            <li>To respond to inquiries and provide consulting services</li>
            <li>To improve our services and tools</li>
            <li>To communicate with you about our services (with your consent)</li>
          </ul>

          <h2 className="text-[1.2rem] font-semibold text-brand-primary mt-8">
            5. AI-generated content
          </h2>
          <p>
            Program frameworks generated by our AI Program Builder are{" "}
            <strong>draft starting points</strong> and do not constitute legal,
            regulatory, or compliance advice. All AI output is explicitly framed as a
            non-binding draft that requires validation and tailoring by qualified
            professionals. Empower&apos;s team reviews and refines all program
            frameworks before implementation.
          </p>

          <h2 className="text-[1.2rem] font-semibold text-brand-primary mt-8">
            6. Data storage and security
          </h2>
          <p>
            Your data is stored securely using Cloudflare infrastructure. All data is
            transmitted over HTTPS. We implement appropriate technical and
            organizational measures to protect your information against unauthorized
            access, alteration, or destruction.
          </p>

          <h2 className="text-[1.2rem] font-semibold text-brand-primary mt-8">
            7. Third-party services
          </h2>
          <p>
            We use Anthropic&apos;s Claude AI to generate program frameworks. School
            profile data (aggregate, non-identifying) is sent to Anthropic&apos;s API
            for processing. No individually identifiable student data is ever sent to
            third-party services.
          </p>

          <h2 className="text-[1.2rem] font-semibold text-brand-primary mt-8">
            8. Your rights
          </h2>
          <p>
            You may request access to, correction of, or deletion of your personal
            information at any time by contacting us. We will respond to all
            requests within a reasonable timeframe.
          </p>

          <h2 className="text-[1.2rem] font-semibold text-brand-primary mt-8">
            9. Contact
          </h2>
          <p>
            For privacy-related questions or requests, please contact us through our{" "}
            <a href="/contact" className="text-brand-primary underline">
              contact page
            </a>
            .
          </p>

          <h2 className="text-[1.2rem] font-semibold text-brand-primary mt-8">
            10. Changes to this policy
          </h2>
          <p>
            We may update this privacy policy from time to time. Changes will be
            posted on this page with an updated effective date.
          </p>
        </div>
      </div>
    </section>
  );
}
